kind: pipeline
name: default

steps:
- name: build
  image: fanux/kubernetes-build:v1.0.0
  commands:
    - make all WHAT=cmd/kubeadm GOFLAGS=-v

- name: publish
  image: plugins/docker
  settings:
    repo: fanux/kubeadm
    tags: ${DRONE_TAG=latest}
    username: fanux
    password:
      from_secret: docker-hub-pass
